---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: querido-diario
data:
  01-init-multiple-databases.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
        CREATE DATABASE backend;
        CREATE DATABASE companies;
        CREATE DATABASE queridodiario;
        GRANT ALL PRIVILEGES ON DATABASE backend TO ${POSTGRES_USER};
        GRANT ALL PRIVILEGES ON DATABASE companies TO ${POSTGRES_USER};
        GRANT ALL PRIVILEGES ON DATABASE queridodiario TO ${POSTGRES_USER};

        \c backend
        GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};

        \c companies
        GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};

        \c queridodiario
        GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${POSTGRES_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};
    EOSQL
    echo "Databases created successfully."
